In [1]:
import torch
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

In [4]:
z = torch.FloatTensor([1, 2, 3])

In [5]:
hypothesis = F.softmax(z, dim = 0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [7]:
hypothesis.sum()

tensor(1.)

In [8]:
z = torch.rand(3, 5, requires_grad = True)

In [9]:
hypothesis = F.softmax(z, dim = 1)    # 각 샘플에 대해서 소프트맥스 함수를 적용해야 하므로 두번째 차원(dim = 1)에 대해서 함수를 적용
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [10]:
y = torch.randint(5, (3, )).long()    # 임의의 레이블 만들기
print(y)

tensor([0, 2, 1])


In [12]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)    # 0, 2, 1 / unsqueeze에서 (3,) -> (3 X 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [13]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim = 1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [14]:
F.log_softmax(z, dim = 1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

In [15]:
# cost

(y_one_hot * -torch.log(hypothesis)).sum(dim = 1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [16]:
# Also cost (No need to use one-hot encoding in y)

F.nll_loss(F.log_softmax(z, dim = 1), y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [17]:
# Also cost

F.cross_entropy(z, y)

tensor(1.4689, grad_fn=<NllLossBackward0>)