In [ ]:
import numpy as np
import torch

# **1D Array with NumPy**

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[2] = ', t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1])  # slicing

t[0] t[1] t[2] =  0.0 1.0 6.0
[2. 3. 4.] [4. 5.]


#**2D Arrray with NumPy**

In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])   # 4 X 3
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


#**1D Array with Pytorch**






In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[2])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(2.)


#**2D Array with Pytorch**


In [ ]:
t = torch. FloatTensor([[1., 2., 3.],
                             [4., 5., 6.],
                             [7., 8., 9.],
                             [10., 11., 12.]    
                             ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#**Broadcasting**

In [ ]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]]) 
m1 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# 1 x 2 vector + 2 x 1 vector
m1 = torch.FloatTensor([[1, 2]])
m1 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.],
        [6., 6.]])


#**Multiplication vs Matrix Multiplication**

In [ ]:
print()
print('------------------')
print(' Mul vs Matmul ')
print('------------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])   # 2 x 2
m2 = torch.FloatTensor([[1], [2]])         # 2 x 1
print('Matmul')
print(m1.matmul(m2))
print('Mul')
print(m1.mul(m2))


------------------
 Mul vs Matmul 
------------------
Matmul
tensor([[ 5.],
        [11.]])
Mul
tensor([[1., 2.],
        [6., 8.]])


#**Mean**

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#**Sum**

In [ ]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#**Max and Argmax**

In [32]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
print(t.max())

tensor(4.)


In [35]:
print(t.max(dim = 0))
print('Max : ', t.max(dim = 0)[0])
print('Argmax : ', t.max(dim = 0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max :  tensor([3., 4.])
Argmax :  tensor([1, 1])


In [36]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
